# Generated by Django 4.2.7 on 2025-07-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_creadted_at_user_created_at_bill_billsplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsplit',
            name='settled_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pool',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='core.user'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
